"""
Database initialization and schema definition for Campus Resource Hub.

This module defines the database schema using SQLite and provides
initialization functions for creating tables and sample data.
"""
# AI Contribution: Schema structure generated by Cursor AI based on project requirements
# Reviewed and validated by team for data integrity and indexing

import sqlite3
from datetime import datetime
import os


DATABASE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'campus_hub.db')


def get_db_connection():
    """
    Create and return a database connection with row factory.
    
    Returns:
        sqlite3.Connection: Database connection object
    """
    conn = sqlite3.connect(DATABASE_PATH)
    conn.row_factory = sqlite3.Row  # Enable column access by name
    conn.execute("PRAGMA foreign_keys = ON")  # Enable foreign key constraints
    return conn


def init_database():
    """
    Initialize the database schema by creating all required tables.
    Drops existing tables if they exist (WARNING: data loss).
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Drop existing tables (in reverse order of dependencies)
    cursor.execute("DROP TABLE IF EXISTS admin_logs")
    cursor.execute("DROP TABLE IF EXISTS reviews")
    cursor.execute("DROP TABLE IF EXISTS messages")
    cursor.execute("DROP TABLE IF EXISTS bookings")
    cursor.execute("DROP TABLE IF EXISTS resources")
    cursor.execute("DROP TABLE IF EXISTS users")
    
    # Create users table
    cursor.execute("""
        CREATE TABLE users (
            user_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL CHECK(role IN ('student', 'staff', 'admin')),
            profile_image TEXT,
            department TEXT,
            google_calendar_token TEXT,
            google_calendar_refresh_token TEXT,
            google_calendar_token_expiry DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    """)
    
    # Create resources table
    cursor.execute("""
        CREATE TABLE resources (
            resource_id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            category TEXT,
            location TEXT,
            capacity INTEGER,
            images TEXT,
            availability_rules TEXT,
            status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'published', 'archived')),
            requires_approval INTEGER DEFAULT 0,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
        )
    """)
    
    # Create bookings table
    cursor.execute("""
        CREATE TABLE bookings (
            booking_id INTEGER PRIMARY KEY AUTOINCREMENT,
            resource_id INTEGER NOT NULL,
            requester_id INTEGER NOT NULL,
            start_datetime DATETIME NOT NULL,
            end_datetime DATETIME NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' 
                CHECK(status IN ('pending', 'approved', 'rejected', 'cancelled', 'completed')),
            notes TEXT,
            calendar_event_id TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (resource_id) REFERENCES resources(resource_id) ON DELETE CASCADE,
            FOREIGN KEY (requester_id) REFERENCES users(user_id) ON DELETE CASCADE
        )
    """)
    
    # Create messages table
    cursor.execute("""
        CREATE TABLE messages (
            message_id INTEGER PRIMARY KEY AUTOINCREMENT,
            thread_id TEXT NOT NULL,
            sender_id INTEGER NOT NULL,
            receiver_id INTEGER NOT NULL,
            booking_id INTEGER,
            content TEXT NOT NULL,
            is_read INTEGER DEFAULT 0,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (sender_id) REFERENCES users(user_id) ON DELETE CASCADE,
            FOREIGN KEY (receiver_id) REFERENCES users(user_id) ON DELETE CASCADE,
            FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE SET NULL
        )
    """)
    
    # Create reviews table
    cursor.execute("""
        CREATE TABLE reviews (
            review_id INTEGER PRIMARY KEY AUTOINCREMENT,
            resource_id INTEGER NOT NULL,
            reviewer_id INTEGER NOT NULL,
            booking_id INTEGER,
            rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
            comment TEXT,
            is_hidden INTEGER DEFAULT 0,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (resource_id) REFERENCES resources(resource_id) ON DELETE CASCADE,
            FOREIGN KEY (reviewer_id) REFERENCES users(user_id) ON DELETE CASCADE,
            FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE SET NULL,
            UNIQUE(reviewer_id, booking_id)
        )
    """)
    
    # Create admin_logs table
    cursor.execute("""
        CREATE TABLE admin_logs (
            log_id INTEGER PRIMARY KEY AUTOINCREMENT,
            admin_id INTEGER NOT NULL,
            action TEXT NOT NULL,
            target_table TEXT,
            target_id INTEGER,
            details TEXT,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (admin_id) REFERENCES users(user_id) ON DELETE CASCADE
        )
    """)
    
    # Create indexes for performance optimization
    cursor.execute("CREATE INDEX idx_users_email ON users(email)")
    cursor.execute("CREATE INDEX idx_users_role ON users(role)")
    cursor.execute("CREATE INDEX idx_resources_owner ON resources(owner_id)")
    cursor.execute("CREATE INDEX idx_resources_status ON resources(status)")
    cursor.execute("CREATE INDEX idx_resources_category ON resources(category)")
    cursor.execute("CREATE INDEX idx_bookings_resource ON bookings(resource_id)")
    cursor.execute("CREATE INDEX idx_bookings_requester ON bookings(requester_id)")
    cursor.execute("CREATE INDEX idx_bookings_datetime ON bookings(start_datetime, end_datetime)")
    cursor.execute("CREATE INDEX idx_bookings_status ON bookings(status)")
    cursor.execute("CREATE INDEX idx_messages_thread ON messages(thread_id)")
    cursor.execute("CREATE INDEX idx_messages_receiver ON messages(receiver_id)")
    cursor.execute("CREATE INDEX idx_reviews_resource ON reviews(resource_id)")
    
    conn.commit()
    conn.close()
    
    print(f"[OK] Database initialized successfully at {DATABASE_PATH}")


def seed_sample_data():
    """
    Populate the database with sample data for testing and demonstration.
    """
    import bcrypt
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Create sample users
    users = [
        ('Admin User', 'admin@university.edu', 'admin123', 'admin', 'IT Department'),
        ('Dr. Sarah Johnson', 'sjohnson@university.edu', 'staff123', 'staff', 'Computer Science'),
        ('Alex Smith', 'asmith@university.edu', 'student123', 'student', 'Business'),
        ('Maria Garcia', 'mgarcia@university.edu', 'student123', 'student', 'Engineering'),
        ('Prof. David Lee', 'dlee@university.edu', 'staff123', 'staff', 'Physics'),
    ]
    
    for name, email, password, role, dept in users:
        password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        cursor.execute(
            "INSERT INTO users (name, email, password_hash, role, department) VALUES (?, ?, ?, ?, ?)",
            (name, email, password_hash, role, dept)
        )
    
    # Create sample resources
    resources = [
        (2, 'Conference Room A', 'Modern conference room with video conferencing', 'Meeting Room', 
         'Business Building, Floor 3', 12, '', '{"weekdays": "8am-8pm"}', 'published', 1),
        (2, 'Study Room 101', 'Quiet individual study space', 'Study Room', 
         'Library, Floor 1', 1, '', '{"24/7": true}', 'published', 0),
        (2, '4K Video Camera Kit', 'Professional camera with tripod and accessories', 'Equipment', 
         'Media Center', 1, '', '{"weekdays": "9am-5pm"}', 'published', 1),
        (5, 'Physics Lab Station', 'Equipped workstation with oscilloscope and tools', 'Lab Space', 
         'Science Building, Room 204', 2, '', '{"weekdays": "8am-10pm"}', 'published', 1),
        (3, 'Group Study Space', 'Collaborative workspace with whiteboard', 'Study Room', 
         'Library, Floor 2', 8, '', '{"always": true}', 'published', 0),
        (2, 'Projector & Screen', 'HD projector with portable screen', 'Equipment', 
         'Media Center', 1, '', '{"weekdays": "9am-5pm"}', 'published', 1),
    ]
    
    for resource in resources:
        cursor.execute("""
            INSERT INTO resources (owner_id, title, description, category, location, capacity, 
                                 images, availability_rules, status, requires_approval)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, resource)
    
    # Create sample bookings
    bookings = [
        (1, 3, '2025-11-11 10:00:00', '2025-11-11 12:00:00', 'approved', 'Team meeting'),
        (2, 3, '2025-11-11 14:00:00', '2025-11-11 16:00:00', 'approved', ''),
        (3, 4, '2025-11-12 09:00:00', '2025-11-12 11:00:00', 'pending', 'Video project for class'),
        (4, 3, '2025-11-13 13:00:00', '2025-11-13 17:00:00', 'approved', 'Lab experiment'),
        (5, 4, '2025-11-10 15:00:00', '2025-11-10 18:00:00', 'completed', 'Study session'),
    ]
    
    for booking in bookings:
        cursor.execute("""
            INSERT INTO bookings (resource_id, requester_id, start_datetime, end_datetime, status, notes)
            VALUES (?, ?, ?, ?, ?, ?)
        """, booking)
    
    # Create sample reviews
    reviews = [
        (1, 3, 1, 5, 'Excellent room! Great for team meetings.'),
        (2, 3, 2, 4, 'Nice quiet space, could use better lighting.'),
        (5, 4, 5, 5, 'Perfect for group work, whiteboard is very useful.'),
    ]
    
    for review in reviews:
        cursor.execute("""
            INSERT INTO reviews (resource_id, reviewer_id, booking_id, rating, comment)
            VALUES (?, ?, ?, ?, ?)
        """, review)
    
    conn.commit()
    conn.close()
    
    print("[OK] Sample data seeded successfully")
    print("\nTest Accounts:")
    print("  Admin:   admin@university.edu / admin123")
    print("  Staff:   sjohnson@university.edu / staff123")
    print("  Student: asmith@university.edu / student123")


if __name__ == '__main__':
    print("Initializing Campus Resource Hub Database...")
    init_database()
    seed_sample_data()
    print("\n[OK] Database setup complete!")

