"""
Main Flask application for Campus Resource Hub.

This module initializes the Flask app, configures extensions,
and registers all blueprints for routing.
"""
# AI Contribution: Flask app structure generated by Cursor AI; team configured security settings

from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager, current_user
import os
from datetime import datetime

# Import blueprints
from src.controllers.auth import auth_bp
from src.controllers.resources import resources_bp
from src.controllers.bookings import bookings_bp
from src.controllers.messages import messages_bp
from src.controllers.admin_panel import admin_bp
from src.controllers.dashboard import dashboard_bp
from src.controllers.ai_chatbot import ai_chatbot_bp
from src.controllers.google_calendar import google_calendar_bp
from src.controllers.analytics import analytics_bp
from src.controllers.analytics_export import export_bp

# Import models
from src.data_access.user_dal import UserDAL


def create_app():
    """
    Application factory function.
    
    Returns:
        Flask: Configured Flask application
    """
    app = Flask(__name__,
                template_folder='views',
                static_folder='static')
    
    # Configuration
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-production')
    app.config['WTF_CSRF_ENABLED'] = True
    app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max upload
    
    # Initialize Flask-Login
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'Please log in to access this page.'
    login_manager.login_message_category = 'warning'
    
    @login_manager.user_loader
    def load_user(user_id):
        """Load user from database for Flask-Login."""
        from src.models.user import User
        user_data = UserDAL.get_user_by_id(int(user_id))
        if user_data:
            return User(user_data)
        return None
    
    # Register blueprints
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(resources_bp, url_prefix='/resources')
    app.register_blueprint(bookings_bp, url_prefix='/bookings')
    app.register_blueprint(messages_bp, url_prefix='/messages')
    app.register_blueprint(admin_bp, url_prefix='/admin')
    app.register_blueprint(dashboard_bp, url_prefix='/dashboard')
    app.register_blueprint(ai_chatbot_bp, url_prefix='/ai')
    app.register_blueprint(google_calendar_bp, url_prefix='/calendar')
    app.register_blueprint(analytics_bp, url_prefix='/analytics')
    app.register_blueprint(export_bp, url_prefix='/analytics/export')
    
    # Context processors - make variables available to all templates
    @app.context_processor
    def inject_globals():
        """Inject global variables into all templates."""
        unread_count = 0
        if current_user.is_authenticated:
            from src.data_access.message_dal import MessageDAL
            unread_count = MessageDAL.get_unread_count(current_user.get_id())
        
        return {
            'current_year': datetime.now().year,
            'unread_message_count': unread_count,
            'ga_measurement_id': os.environ.get('GA_MEASUREMENT_ID', '')
        }
    
    # Error handlers
    @app.errorhandler(404)
    def not_found_error(error):
        return render_template('errors/404.html'), 404
    
    @app.errorhandler(500)
    def internal_error(error):
        return render_template('errors/500.html'), 500
    
    @app.errorhandler(403)
    def forbidden_error(error):
        return render_template('errors/403.html'), 403
    
    # Home route
    @app.route('/')
    def index():
        """Homepage with search and featured resources."""
        from src.data_access.resource_dal import ResourceDAL
        from src.data_access.review_dal import ReviewDAL
        
        # Get recent and top-rated resources
        recent_resources = ResourceDAL.search_resources(sort_by='recent')[:6]
        top_rated = ReviewDAL.get_top_rated_resources(limit=6)
        categories = ResourceDAL.get_all_categories()
        
        return render_template('index.html', 
                             recent_resources=recent_resources,
                             top_rated_resources=top_rated,
                             categories=categories)
    
    # Health check endpoint
    @app.route('/health')
    def health_check():
        return {'status': 'healthy', 'app': 'Campus Resource Hub'}, 200
    
    return app


if __name__ == '__main__':
    # Initialize database if it doesn't exist
    from src.models.database import DATABASE_PATH, init_database, seed_sample_data
    import os
    
    if not os.path.exists(DATABASE_PATH):
        print("Database not found. Initializing...")
        init_database()
        seed_sample_data()
    
    # Create and run app
    app = create_app()
    app.run(debug=True, host='0.0.0.0', port=5000)

